version: '3'
services:

  web:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    # depends_on:
    #   - flask
  flaskGetPrice:
    build: .
    restart: always
    environment:
      - GUNICORN_HOST=0.0.0.0
      - GUNICORN_PORT=5001
    # volumes:
    #   - .:/app
    expose:
      - "5001"


volumes:
  app: